server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/software_engine_design?useSSL=false
    password: 1234
    username: root
  main:
    banner-mode: off
  mail:
    port: 465
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: #xxx@qq.com
    #授权码
    password: #xxx
    test-connection: true
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: assign_id
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

